name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd ~/apps/GasStationManagerApp
          git pull origin main

      - name: Build backend (skip tests)
        run: |
          cd ~/apps/GasStationManagerApp/backend
          ./mvnw clean package -DskipTests

      - name: Restart Docker
        run: |
          cd ~/apps/GasStationManagerApp
          docker-compose down
          docker-compose up -d --build
