name: Deploy Dev to Raspberry Pi

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd ~/apps/GasStationManagerApp
          git fetch origin dev
          git reset --hard origin/dev

      - name: Build backend (skip tests)
        run: |
          cd ~/apps/GasStationManagerApp/backend
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests

      - name: Restart Dev Docker
        run: |
          cd ~/apps/GasStationManagerApp
          COMPOSE_PROJECT_NAME=gasstationmanagerapp_dev docker-compose -f docker-compose.dev.yml down
          COMPOSE_PROJECT_NAME=gasstationmanagerapp_dev docker-compose -f docker-compose.dev.yml up -d --build
      - name: Notify deployment success
        run: |
          echo "Deployment to Dev environment successful!"
          # Optionally, you can add a notification step here (e.g., Slack, email)
      - name: Clean up old images
        run: |
          docker image prune -f
          docker volume prune -f
          echo "Old images and volumes cleaned up."
      - name: Check Docker status
        run: |
          docker ps -a
          echo "Current Docker containers status displayed."  
          # This step is optional but can help in debugging if something goes wrong
