name: Generate SSH Key

on:
  workflow_dispatch:   # lets you manually trigger this workflow from GitHub UI

jobs:
  generate-key:
    runs-on: ubuntu-latest

    steps:
      - name: Generate SSH key
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t ed25519 -C "ci-deploy-key" -f ~/.ssh/ci_deploy_key -N ""

      - name: Show public key
        run: cat ~/.ssh/ci_deploy_key.pub
